version: '3.8'

services:
  app:
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certificates:/etc/letsencrypt  
    depends_on:
      - app

volumes:
  pgdata:
